### ISSUE TITLE
HTML showing on the "Add New Assistant" page 

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#22]
Steps to locate:

Navigate to the Admin panel.
Go to BuddyBot -> Assistant.
Click on Create New Assistant 

<img width="670" alt="image" src="https://github.com/user-attachments/assets/258615ea-f604-448a-8ca0-acc8ea8efe45">

**Comment by Bhimashankar3002** [comment]
CHECK
