### ISSUE TITLE
Infinite Loading When Entering a Long Name for BuddyBot

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#23]
Steps to reproduce:

Navigate to the Admin panel.
Go to BuddyBot.
Add New BuddyBot.
Enter a long name in the Name field.
And it starts loading endlessly

![image](https://github.com/user-attachments/assets/c9a8c637-0275-4412-adc7-0757296ffe0f)

**Comment by Bhimashankar3002** [comment]
CHECK
