### ISSUE TITLE
Deleted Assistant Still Linked on Edit BuddyBot Page

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#24]
Steps to reproduce:

Navigate to the Admin panel.
Go to BuddyBot -> Assistant and delete an assistant.
Navigate to BuddyBot and click Edit on any existing BuddyBot.
Expected Behavior:
If an assistant linked to the BuddyBot is deleted, it should no longer appear on the Edit BuddyBot page or be associated with the BuddyBot.

Actual Behavior:
The deleted assistant still appears to be linked or displayed on the Edit BuddyBot page, even though it no longer exists.

![image](https://github.com/user-attachments/assets/fce97944-9f15-42bd-926b-1f292b19889d)
![image](https://github.com/user-attachments/assets/378107eb-b1b4-49be-acc1-c7896a94a428)

**Comment by Bhimashankar3002** [comment]
CHECK
