### ISSUE TITLE
Assistant name too long, breaks UI on Playground page

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#26]
When the assistant name is too long, it causes the UI to break on the Playground page. The text overflows or overlaps, making it difficult to read and interact with the interface.

Steps to Reproduce
Set the assistant name to a long string (e.g., "SuperLongAssistantNameThatDoesNotFit").
Navigate to the Playground page.
Observe how the UI layout is affected by the long name.

![image](https://github.com/user-attachments/assets/254d61d3-4e70-41ce-867a-a82c823bcb5c)

**Comment by Bhimashankar3002** [comment]
CHECK
