### ISSUE TITLE
Add help text for dropdown usage explanation

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#28]
Provide a brief helptext explaining the purpose and functionality of the dropdown in the Admin > Buddybot > Settings page. This will help users understand why they need to use it.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/aa67e5d9-996f-4872-bcc6-37c3dc687c42">

**Comment by Bhimashankar3002** [comment]
CHECK
