### ISSUE TITLE
Fix Horizontal Scroll Issue on Assistant Page

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#29]
Steps to Reproduce:

Navigate to the Assistant page.
Observe the horizontal scrollbar appearing if you enter the long name of assistant.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/4851b80b-554a-4c1d-842a-4b6d9272c3e9">

**Comment by Bhimashankar3002** [comment]
CHECK
