### ISSUE TITLE
Replace Bootstrap-specific alert classes with WordPress native styling.

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#3]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/b8d1bd28-2b39-4730-b0bb-4ffb9d2d1889">

### **Issue Description**  
The current alert uses Bootstrap-specific classes (`alert alert-danger`) which do not align with WordPress admin styling guidelines. The alert appears as follows:  

```html
<div class="alert alert-danger small mb-3" role="alert">
    OpenAI API Key Missing. Please save it 
    <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-settings">here.</a>
</div>
```

### **Improvements**  
- Replace the Bootstrap classes with WordPress-native classes (`notice notice-error`) for better compatibility.  
- Update the alert format to:  

```html
<div class="notice notice-error">
    <p>
        <strong>BuddyBot Notice:</strong> OpenAI API Key is missing. Please configure your API Key to enable BuddyBot's features. 
        <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-settings">Go to Settings</a>.
    </p>
</div>
```

**Comment by Bhimashankar3002** [comment]
CHECK
