### ISSUE TITLE
Display "Select Assistant" or "No Assistant Available" Based on Availability

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#30]
Currently, the assistant dropdown does not update based on the availability of assistants. If there are assistants available, it should show "Select Assistant." If no assistants are available, it should either show "No Assistant Available" or grey out the dropdown to prevent selection.
Admin -> BuddyBot ->Playground

<img width="841" alt="image" src="https://github.com/user-attachments/assets/03d95c6d-1b11-4e59-855a-de2489fa1fdf">

**Comment by Bhimashankar3002** [comment]
CHECK
