### ISSUE TITLE
Add Placeholder Text to the Search Bar

### ISSUE THREAD

**Issue by metagauss-controls** [Metagauss-com/buddybot#31]
The search bar currently lacks a placeholder text, which may leave users unsure about what to search for. Adding placeholder text will guide users and improve the overall user experience.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/1e38ec7d-6190-430a-adf2-95b3ada51193">

**Comment by metagauss** [comment]
- **Placeholder Text**:  
  `"Type your question or message here..."`

**Comment by Bhimashankar3002** [comment]
CHECK
