### ISSUE TITLE
Present this error as a steps to create buddybot

### ISSUE THREAD

**Issue by Bhimashankar3002** [Metagauss-com/buddybot#32]
![image](https://github.com/user-attachments/assets/22dabc52-1491-4b21-bb82-a764871dd548)

**Comment by metagauss** [comment]
[BuddyBot_Setup_Banner_With_Graphic.html.zip](https://github.com/user-attachments/files/18111114/BuddyBot_Setup_Banner_With_Graphic.html.zip)

@shubham9649 use this design. Take help of @mJawed to improve icon.

**Comment by Bhimashankar3002** [comment]
CHECK
