### ISSUE TITLE
Mask sensitive API keys in the Settings area to enhance security.

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#4]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/c3a4e94e-b3cf-432c-83f5-55408f9008c1">

### **1. Mask the API Key Input**

- **Change the `input` type from `text` to `password`** to mask the API key and prevent it from being displayed in plain text.

  ```html
  <tr>
    <th><label for="buddybot-settings-openai-api-key">OpenAI API Key</label></th>
    <td>
      <input type="password" id="buddybot-settings-openai-api-key" name="buddybot_openai_api_key" value="" class="regular-text">
      <p class="description">Your OpenAI API key.</p>
    </td>
  </tr>
  ```

  - **Note**: Leave the `value` attribute empty or populate it securely on the server side without exposing the key in the HTML source.

### **2. Add a Show/Hide Toggle Button**

- Include a button that allows the admin to toggle the visibility of the API key. This enhances usability while maintaining security.

  ```html
  <tr>
    <th><label for="buddybot-settings-openai-api-key">OpenAI API Key</label></th>
    <td>
      <input type="password" id="buddybot-settings-openai-api-key" name="buddybot_openai_api_key" value="" class="regular-text">
      <button type="button" id="toggle-api-key-visibility" class="button">Show</button>
      <p class="description">Your OpenAI API key.</p>
    </td>
  </tr>
  ```

- **JavaScript for Toggle Functionality**:

  ```javascript
  <script>
  document.getElementById('toggle-api-key-visibility').addEventListener('click', function () {
    const apiKeyField = document.getElementById('buddybot-settings-openai-api-key');
    if (apiKeyField.type === 'password') {
      apiKeyField.type = 'text';
      this.textContent = 'Hide';
    } else {
      apiKeyField.type = 'password';
      this.textContent = 'Show';
    }
  });
  </script>
  ```

### **3. Securely Handle the API Key Value**

- **Avoid Rendering the API Key in the HTML Source**:

  - Do not include the actual API key in the `value` attribute when rendering the page. This prevents exposure of the key in the page source or browser developer tools.

- **Retrieve and Populate the API Key Securely**:

  - If you need to indicate that an API key has been set without displaying it, consider showing placeholder text or a message like "API key is set."

  ```html
  <input type="password" id="buddybot-settings-openai-api-key" name="buddybot_openai_api_key" placeholder="Enter your API key" class="regular-text">
  ```

### **4. Use WordPress Settings API for Saving Data**

- Utilize the [WordPress Settings API](https://developer.wordpress.org/plugins/settings/settings-api/) to handle the saving and retrieval of the API key securely. This includes proper data sanitization and user capability checks.

### **5. Implement Proper Labeling and Help Text**

- Ensure that the label and description provide clear guidance to the admin.

  ```html
  <p class="description">Enter your OpenAI API key. This key allows BuddyBot to access OpenAI services.</p>
  ```

### **6. Add Input Field Attributes for Security**

- **Autocomplete Attribute**:

  - Disable autocomplete to prevent the browser from storing the API key.

    ```html
    <input type="password" id="buddybot-settings-openai-api-key" name="buddybot_openai_api_key" autocomplete="off" class="regular-text">
    ```

**Comment by metagauss** [comment]
### **Improved Description**

### **Full Updated Row with Description**
Here’s the complete row with the updated description:

```html
<tr>
    <th><label for="buddybot-settings-openai-api-key">OpenAI API Key</label></th>
    <td>
        <input type="password" id="buddybot-settings-openai-api-key" name="buddybot_openai_api_key" autocomplete="off" class="regular-text">
        <button type="button" id="toggle-api-key-visibility" class="button">Show</button>
        <p class="description">
            Enter your OpenAI API key to enable BuddyBot's functionality. 
            <a href="https://platform.openai.com/signup" target="_blank">Sign up for an OpenAI account</a> 
            if you don’t have one, and generate your API key in the 
            <a href="https://platform.openai.com/account/api-keys" target="_blank">API Keys section</a>. 
            Ensure the key has appropriate permissions for the intended operations.
        </p>
    </td>
</tr>
```

---

Let me know if you’d like further tweaks or additional suggestions!

**Comment by Bhimashankar3002** [comment]
CHECK
