### ISSUE TITLE
Replace Bootstrap-specific alert classes and improve messaging for the "Vector Store Missing" alert.

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#5]
### **Issue Description**  
The current alert for a missing vector store uses Bootstrap-specific classes and has a minimal explanation of the problem. Here's the current alert:

```html
<div class="alert alert-danger small mb-3" role="alert">
    Vector Store Missing. Please create it 
    <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-vectorstore">here.</a>
</div>
```

### **Improvements**  

1. **Replace Bootstrap Classes with WordPress Native Styling**
   Update the alert to use WordPress-native classes for consistency within the admin dashboard:
   ```html
   <div class="notice notice-error">
       <p>
           <strong>BuddyBot Notice:</strong> No vector store detected. A vector store is required for BuddyBot to function properly. 
           Please create one by clicking <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-vectorstore">here</a>.
       </p>
   </div>
   ```

2. **Enhance the Message**
   - **Clarity**: Explain why the vector store is needed.
   - **Actionable Guidance**: Include a link to the settings page for creating the vector store.
   - **Error Context**: Indicate that this is part of the initial setup.

3. **Dismissible Alert**
   Add the `is-dismissible` class so that users can remove the alert after reading.

4. **Optional Contextual Help**
   Provide a link to documentation or a tooltip explaining what a vector store is and why it’s necessary:
   ```html
   <div class="notice notice-error">
       <p>
           <strong>BuddyBot Notice:</strong> No vector store detected. A vector store is required to manage and retrieve contextual data for BuddyBot. 
           Please create one by clicking <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-vectorstore">here</a>. 
           <a href="https://docs.metagauss.com/buddybot/vectorstore" target="_blank">(Learn more)</a>.
       </p>
   </div>
   ```

---

### **Final Alert Example**

Here’s the improved alert in HTML:

```html
<div class="notice notice-error">
    <p>
        <strong>BuddyBot Notice:</strong> No vector store detected. A vector store is required to manage and retrieve contextual data for BuddyBot. 
        Please create one by clicking <a href="https://neimf.metagauss.net/wp-admin/admin.php?page=buddybot-vectorstore">here</a>. 
        <a href="https://docs.metagauss.com/buddybot/vectorstore" target="_blank">(Learn more)</a>.
    </p>
</div>
```

**Comment by Bhimashankar3002** [comment]
CHECK
