### ISSUE TITLE
need a new svg logo for the attached screenshot:

### ISSUE THREAD

**Issue by shubham9649** [Metagauss-com/buddybot#58]
![svglogo](https://github.com/user-attachments/assets/c743bc4a-f1a8-48c2-b2cb-2a76d536f777)

**Comment by metagauss** [comment]
![176093490_79e15047-1f35-4656-92e8-a547c4a1f8df](https://github.com/user-attachments/assets/0911466a-de9d-4412-96a3-065e1314a4a9)

@mJawed please improve this logo for use in BB

**Comment by Bhimashankar3002** [comment]
CHECK
