### ISSUE TITLE
Improved HTML for "Create Vector Store" Section

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#6]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/a8c60792-285f-4e4a-b9c8-5ae85d80e647">

### **Improved HTML for "Create Vector Store" Section**

```html
<div id="buddybot-vectorstore-section" class="notice notice-warning">
    <p>
        <strong>No Vector Store Found:</strong> BuddyBot requires a vector store to manage and retrieve contextual data. 
        Click the button below to create one.
    </p>
    <p>
        <button id="buddybot-vectorstore-create" class="button button-primary" type="button">
            <span class="buddybot-loaderbtn-label">Create Vector Store</span>
            <span class="spinner buddybot-loaderbtn-spinner" aria-hidden="true" style="display: none;"></span>
        </button>
    </p>
</div>
```

---

### **Using WordPress Spinner**
The `spinner` class is part of WordPress core styling, and you can control its visibility using JavaScript.

---

### **JavaScript for Spinner Behavior**

```javascript
document.getElementById('buddybot-vectorstore-create').addEventListener('click', function () {
    const label = this.querySelector('.buddybot-loaderbtn-label');
    const spinner = this.querySelector('.buddybot-loaderbtn-spinner');

    // Update button state
    label.textContent = 'Creating...';
    spinner.style.display = 'inline-block';

    // Simulate API Call
    setTimeout(() => {
        // Reset button state
        label.textContent = 'Create Vector Store';
        spinner.style.display = 'none';
        alert('Vector Store Created Successfully!');
    }, 2000); // Replace with actual API call
});
```

---

### **Benefits of Using the WordPress Spinner**
1. **Consistency**: Matches the WordPress admin interface.
2. **No Additional Styling Required**: The `spinner` class is styled by WordPress core, ensuring seamless integration.
3. **Simplicity**: Reduces the need for custom CSS.

---

### **Final Output**

The spinner will now display inline with the button when the creation process starts and will disappear after completion.

**Comment by Bhimashankar3002** [comment]
CHECK
