### ISSUE TITLE
New Fields in Edit Assistance View

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#67]
- **Issue Title:** Add 'Friendly Name' Field on Edit Assistant Page

  **Description:**
  Add a new field titled "Friendly Name" on the Edit Assistant page to define a user-friendly name for the assistant. This name will be used during chat sessions and can be referenced in instructions sent to the OpenAI server. Save this data as a meta key (`buddybot_friendly_name`) in the assistant metadata on the OpenAI server.

  **Acceptance Criteria:**
  1. A text input field labeled "Friendly Name" is added to the Edit Assistant page.
     - Placeholder: "e.g., Sarah, Max, BuddyBot."
     - Description: "Define a user-friendly name for the assistant. This name will be used during chat sessions."
  2. Include the value of this field in the instruction payload sent to OpenAI.
  3. Save the field value as a meta key (`buddybot_friendly_name`) in OpenAI assistant metadata.

  **Tasks:**
  - [ ] Add a new input field labeled "Friendly Name" on the Edit Assistant page.
  - [ ] Modify the API call to include the friendly name in the instruction payload.
  - [ ] Ensure the friendly name is saved as a meta key (`buddybot_friendly_name`) in OpenAI assistant metadata.
  - [ ] Test the assistant's behavior with the assigned friendly name during chat.

  **Expected Result:**
  Users can define and save a custom friendly name for the assistant, and the assistant utilizes this name in responses when appropriate.

---

- **Issue Title:** Add 'Initial Greeting' Field on Edit Assistant Page

  **Description:**
  Add a new field titled "Initial Greeting" on the Edit Assistant page. This field allows users to define the greeting message the assistant will use to welcome users at the start of new chat threads. Save this greeting as a meta key (`buddybot_initial_greeting`) for easy retrieval and use in chat sessions.

  **Acceptance Criteria:**
  1. A text input or textarea field labeled "Initial Greeting" is added to the Edit Assistant page.
  2. Placeholder: "e.g., Hi there! How can I assist you today?"
  3. Description: "Set the greeting message the assistant will use to welcome users in new chat threads."
  4. Include the value of this field in the assistant metadata as `buddybot_initial_greeting`.
  5. Display the greeting message at the start of all new chat threads.

  **Tasks:**
  - [ ] Add a new input/textarea field labeled "Initial Greeting" on the Edit Assistant page.
  - [ ] Save the value of this field as `buddybot_initial_greeting` in the assistant metadata.
  - [ ] Ensure the greeting is displayed in new chat threads initiated with the assistant.
  - [ ] Test the greeting message functionality in various scenarios.

  **Expected Result:**
  Users can define a custom initial greeting for the assistant, and the assistant uses this greeting message to welcome users in new chat threads.

**Comment by Bhimashankar3002** [comment]
CHECK
