### ISSUE TITLE
Hide the vector store creation button after creation and improve the message formatting

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#8]
### **Issue Description**  
Once a vector store is created, the page refreshes and still displays the button for creating a vector store. Since this button is no longer needed, it should be removed entirely. Additionally, the message displayed about the created vector store needs better formatting for clarity and consistency with WordPress admin UI.

Current message:
```html
<div id="buddybot-get-vectorstore" class="text-center small">
    <div id="buddybot-vectorstoreData">
        <p>
            <span id="buddybot-vectorstoreName">Vector Store Created with Name: neimf.metagauss.net</span>
        </p>
    </div>
</div>
```

---

### **Improvements**

1. **Remove the Button After Vector Store Creation**
   - In the PHP logic that generates this page, add a condition to check if a vector store exists. If it does, do not output the button.

   **PHP Example**:
   ```php
   if ( empty( $vectorstore_id ) ) {
       echo '<div><button id="buddybot-vectorstore-create" class="button button-primary" type="button">
               <span class="buddybot-loaderbtn-label">Create Vector Store</span>
               <span class="spinner buddybot-loaderbtn-spinner" aria-hidden="true" style="display: none;"></span>
             </button></div>';
   }
   ```

2. **Improve Message Formatting**
   - Update the success message to align with WordPress admin UI and use a cleaner format.

   **Improved HTML for Message**:
   ```html
   <div id="buddybot-get-vectorstore" class="notice notice-success">
       <p>
           <strong>Vector Store Created:</strong> Your vector store has been created successfully. The name of the vector store is: 
           <span class="vectorstore-name">neimf.metagauss.net</span>.
       </p>
   </div>
   ```

---

### **Behavior Changes**

1. **Before Vector Store Creation**:
   - The **Create Vector Store** button is displayed.

2. **After Vector Store Creation**:
   - The button is no longer displayed.
   - A success message replaces the button, formatted consistently with WordPress admin UI standards.

---

### **Benefits of This Change**

1. **Cleaner UI**:
   - Avoids displaying unnecessary elements like a disabled button after the vector store is created.

2. **Consistent Messaging**:
   - Provides a clear, polished success message that follows WordPress conventions.

**Comment by Bhimashankar3002** [comment]
CHECK
