### ISSUE TITLE
HelpText required for the attached screenshot

### ISSUE THREAD

**Issue by shubham9649** [Metagauss-com/buddybot#80]
![vector store delete](https://github.com/user-attachments/assets/dfe50c7c-7102-4c09-9e7e-6e2c4eea6f8f)

![helptext](https://github.com/user-attachments/assets/47fa0170-3193-406a-b8e3-725a2f1e0bf2)

![error of diffrent user](https://github.com/user-attachments/assets/b5817943-c84a-4d0b-ba30-8c7f20c1c09d)

**Comment by metagauss** [comment]
### **Scenario 1: Button to Create Vector Store on the Same Page**

#### **Notice Title:**  
**Unable to Access Vector Store**

#### **Notice Content:**  
"We couldn’t access the vector store. This might happen if the vector store was deleted or the OpenAI API key was changed. Please verify the vector store exists and ensure the correct API key is configured in the [Settings](admin.php?page=buddybot-settings). Or, use the button below to create a new vector store."

---

### **Scenario 2: Link to Page with Create Vector Store Button**

#### **Notice Title:**  
**Unable to Access Vector Store**

#### **Notice Content:**  
"We couldn’t access the vector store. This might happen if the vector store was deleted or the OpenAI API key was changed. Please verify the vector store exists and ensure the correct API key is configured in the [Settings](admin.php?page=buddybot-settings). Or to create a new vector store, please visit the [Vector Store page](admin.php?page=buddybot-vectorstore)."

**Comment by metagauss** [comment]
This conversation belongs to another user. Please start a new conversation to continue.

**Comment by Bhimashankar3002** [comment]
CHECK
