### ISSUE TITLE
Handle cURL timeout error gracefully during file synchronization check

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#9]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7173b7b3-9a44-4d12-a5ce-9b99aad6802f">

### **Issue Title**  
Handle cURL timeout error gracefully during file synchronization check.

---

### **Issue Description**  
When the page loads and performs an AJAX request to check file existence on the OpenAI server, the following error was encountered during testing in the comments section:

**Error Message**:  
`cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received`

This occurs when the request to the OpenAI server exceeds the timeout period without receiving a response.

---

### **Improvements**

1. **Increase cURL Timeout Duration**
   - Extend the timeout duration to allow the OpenAI server more time to respond, especially during high server load scenarios.
   - Example PHP adjustment:
     ```php
     $args = [
         'timeout' => 10, // Increase timeout to 10 seconds
     ];
     $response = wp_remote_get( $url, $args );
     ```

2. **Handle Timeout Errors Gracefully**
   - If a timeout error occurs, display a user-friendly message instead of the raw error.
   - Example:
     ```php
     if ( is_wp_error( $response ) && $response->get_error_code() === 'http_request_failed' ) {
         $error_message = __( 'Unable to verify file status due to a network timeout. Please try again later.' );
         wp_send_json_error( $error_message );
         return;
     }
     ```

3. **Retry Mechanism**
   - Implement a retry mechanism for AJAX requests to handle transient issues.
   - Example JavaScript:
     ```javascript
     function checkFileStatus(retries = 3) {
         jQuery.ajax({
             url: ajaxurl,
             method: 'POST',
             data: {
                 action: 'buddybot_check_file_status',
                 file_type: 'comments',
             },
             success: function (response) {
                 if (response.success) {
                     jQuery('#buddybot-remote-file-status-comments').text('File synchronized.');
                 } else {
                     jQuery('#buddybot-remote-file-status-comments').text(response.data);
                 }
             },
             error: function () {
                 if (retries > 0) {
                     checkFileStatus(retries - 1);
                 } else {
                     jQuery('#buddybot-remote-file-status-comments').text('Unable to verify file status. Please try again later.');
                 }
             },
         });
     }

     // Call the function
     checkFileStatus();
     ```

4. **Error Message in UI**
   - Update the UI to display a more descriptive error message if a timeout occurs:
     ```html
     <div class="notice notice-warning">
         <p>
             <strong>Warning:</strong> Unable to verify file synchronization status due to a network timeout. Please refresh the page or try again later.
         </p>
     </div>
     ```
---

### **Benefits of These Changes**

1. **Improved User Experience**:
   - Users won’t see raw error messages and will receive meaningful feedback instead.
   
2. **Increased Reliability**:
   - Extended timeout and retry mechanisms ensure the system is more resilient to temporary network issues.

3. **Easier Debugging**:
   - Logging errors helps track down and resolve recurring issues more effectively.

**Comment by Bhimashankar3002** [comment]
CHECK
